
package main;

import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import StringDB.DBFile;
import StringDB.DBFormat;
import StringDB.Register;
import StringDB.KeyField;


public class ClientDataBase extends javax.swing.JFrame {

    DBFormat format = new DBFormat(new File("format.xml"));
    DBFormat rentfor = new DBFormat("renta", new String[]{"id", "cedula", "matricula", "fecha", "dias de alquiler"}, new int[]{42, 10, 10, 10, 12}, 0);
    RentalModel model;

    DBFile file;
    DBFile rentals;
    Register current;

    /**
     * Creates new form BankDataBase
     */
    public ClientDataBase() {
        initComponents();
        try {
            file = new DBFile(format, "table.sdb");
            rentals = new DBFile(rentfor, "rentals.sdb");
            KeyField[] f = file.getKeyFields();
            Arrays.sort(f);
            jList1.setListData(f);
        } catch (IOException ex) {
            System.out.println("getKeys error: " + ex);
        }
        SaveButt.setEnabled(false);
        DelButt.setEnabled(false);
        addRenButt.setEnabled(false);
        delRenButt.setEnabled(false);
        file.addDBChangueListener((int ChangueType, Register target) -> {
            System.out.println("fire changue event");
            if (ChangueType != DBFile.DBChangueListener.UPDATE_CHANGUE) {
                System.out.println("    update list event");
                try {
                    KeyField[] f = file.getKeyFields();
                    Arrays.sort(f);
                    jList1.setListData(f);
                } catch (IOException ex) {
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        IDField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dayField = new javax.swing.JFormattedTextField();
        mothField = new javax.swing.JFormattedTextField();
        yearField = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        bronzeField = new javax.swing.JRadioButton();
        silverField = new javax.swing.JRadioButton();
        GoldField = new javax.swing.JRadioButton();
        zaphirField = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        addRenButt = new javax.swing.JButton();
        delRenButt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jToolBar1 = new javax.swing.JToolBar();
        newButt = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        SaveButt = new javax.swing.JButton();
        DelButt = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        vehicleTable1 = new main.VehicleTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(110);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jLabel1.setText("cedula");

        jLabel2.setText("Nombre y apellidos");

        jLabel3.setText("fecha de nacimiento");

        jLabel5.setText("email");

        dayField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        dayField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        dayField.setText("1");

        mothField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        mothField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mothField.setText("1");
        mothField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothFieldActionPerformed(evt);
            }
        });

        yearField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        yearField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        yearField.setText("2000");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(bronzeField);
        bronzeField.setText("bronce");

        buttonGroup1.add(silverField);
        silverField.setText("plata");
        silverField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silverFieldActionPerformed(evt);
            }
        });

        buttonGroup1.add(GoldField);
        GoldField.setText("oro");

        buttonGroup1.add(zaphirField);
        zaphirField.setText("zafiro");
        zaphirField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zaphirFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("cuenta tipo :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zaphirField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoldField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(silverField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bronzeField)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(GoldField)
                    .addComponent(silverField)
                    .addComponent(bronzeField)
                    .addComponent(zaphirField)))
        );

        addRenButt.setText("+");
        addRenButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRenButtActionPerformed(evt);
            }
        });

        delRenButt.setText("-");
        delRenButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delRenButtActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jList2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailField)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addRenButt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delRenButt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(dayField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mothField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mothField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addRenButt)
                        .addComponent(delRenButt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel1);

        jToolBar1.setRollover(true);

        newButt.setText("nuevo");
        newButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtActionPerformed(evt);
            }
        });
        jToolBar1.add(newButt);
        jToolBar1.add(jSeparator2);

        SaveButt.setText("guardar");
        SaveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtActionPerformed(evt);
            }
        });
        jToolBar1.add(SaveButt);

        DelButt.setText("eliminar");
        DelButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelButtActionPerformed(evt);
            }
        });
        jToolBar1.add(DelButt);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                .addGap(1, 1, 1))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSplitPane1)
                .addGap(1, 1, 1))
        );

        jTabbedPane1.addTab("Clientes", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(vehicleTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(vehicleTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        jTabbedPane1.addTab("Vehiculos", jPanel6);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed
        if (evt.getClickCount() > 1) {
            IDField.setEditable(false);
            try {
                file.seek(jList1.getSelectedValue().getIndex());
                current = file.getRegister();
                //lee cedula
                IDField.setText(current.getField(0));
                //lee nombre
                NameField.setText(current.getField(1));
                //lee fecha de nacimiento
                Date birth = new Date(current.getField(2), '/');
                //asigna a campos de fecha
                dayField.setText(birth.getDay() + "");
                mothField.setText(birth.getMoth() + "");
                yearField.setText(birth.getYear() + "");
                emailField.setText(current.getField(3));
                //lee tipo de cuenta
                String type = current.getField(4);
                zaphirField.setSelected(type.indexOf('z') != -1);
                GoldField.setSelected(type.indexOf('g') != -1);
                silverField.setSelected(type.indexOf('s') != -1);
                bronzeField.setSelected(type.indexOf('b') != -1);

                model = new RentalModel(rentals, current.getField(0));
                jList2.setModel(model);
            } catch (IOException ex) {
                System.out.println("read register exception: " + ex.getLocalizedMessage());
            }
            SaveButt.setEnabled(current != null);
            DelButt.setEnabled(current != null);
            addRenButt.setEnabled(current != null);
            delRenButt.setEnabled(current != null);
        }
    }//GEN-LAST:event_jList1MousePressed

    private void SaveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtActionPerformed
        try {
            if (IDField.isEditable()) {
                for (String key : file.getKeys()) {
                    if (key.trim().equals(IDField.getText().trim())) {
                        JOptionPane.showMessageDialog(rootPane, "Clave Invalida\n\ncedula duplicada", "ERROR", JOptionPane.WARNING_MESSAGE);
                        if (current.getField(0).trim().equals("-1")) {

                            file.deleteRegister(current.getIndex());
                        }
                        return;
                    }
                }
            }
            current.setField(0, IDField.getText());
            current.setField(1, NameField.getText());
            current.setField(2, new Date(Integer.parseInt(dayField.getText()), Integer.parseInt(mothField.getText()), Integer.parseInt(yearField.getText())).toString());
            current.setField(3, emailField.getText());
            current.setField(4, zaphirField.isSelected() ? "z".trim() : GoldField.isSelected() ? "g".trim() : GoldField.isSelected() ? "s".trim() : "b".trim());

        } catch (IOException ex) {
            System.out.println("write register exception: " + ex.getLocalizedMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_SaveButtActionPerformed

    private void newButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtActionPerformed

        try {
            if (file.IndexOf("-1") != -1) {
                return;
            }
            IDField.setEditable(false);
            SaveButt.setEnabled(true);
            DelButt.setEnabled(true);
            Register reg = file.addRegister();
            current = reg;
            reg.setField(0, "-1");
            reg.setField(2, "1/1/2000");
            dayField.setText("1");
            mothField.setText("1");
            yearField.setText("2000");
            emailField.setText("");
            IDField.setEditable(true);
            model = new RentalModel(rentals, "-1");
            jList2.setModel(model);
        } catch (IOException ex) {
            System.out.println("add register exception: " + ex.getLocalizedMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_newButtActionPerformed

    private void DelButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelButtActionPerformed
        try {
            file.deleteRegister(current.getIndex());
        } catch (IOException ex) {
            System.out.println("delete register exception: " + ex.getLocalizedMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_DelButtActionPerformed

    private void silverFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silverFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_silverFieldActionPerformed

    private void zaphirFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zaphirFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zaphirFieldActionPerformed

    private void mothFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothFieldActionPerformed

    private void addRenButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRenButtActionPerformed
        try {
            String[] datas = AddPanel.showAddDialog(this, vehicleTable1.model);
            if (datas == null) {
                return;
            }
            model.add(datas, current.getField(0));
        } catch (IOException ex) {
            System.out.println("error add rental " + ex);
        }
    }//GEN-LAST:event_addRenButtActionPerformed

    private void delRenButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delRenButtActionPerformed
        if (jList2.getSelectedIndex() != -1) {
            try {
                int ind = jList2.getSelectedIndex();
                model.removeField(ind);
            } catch (IOException ex) {
                Logger.getLogger(ClientDataBase.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_delRenButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientDataBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientDataBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientDataBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientDataBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientDataBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DelButt;
    private javax.swing.JRadioButton GoldField;
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField NameField;
    private javax.swing.JButton SaveButt;
    private javax.swing.JButton addRenButt;
    private javax.swing.JRadioButton bronzeField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField dayField;
    private javax.swing.JButton delRenButt;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<StringDB.KeyField> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JFormattedTextField mothField;
    private javax.swing.JButton newButt;
    private javax.swing.JRadioButton silverField;
    private main.VehicleTable vehicleTable1;
    private javax.swing.JFormattedTextField yearField;
    private javax.swing.JRadioButton zaphirField;
    // End of variables declaration//GEN-END:variables
}
